# Generated by Django 3.0.5 on 2023-04-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230409_0833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
    ]
