# Generated by Django 3.0.5 on 2023-04-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230409_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
