# Generated by Django 4.2 on 2023-04-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='brand',
            name='headquarters',
            field=models.CharField(default='USA', max_length=50),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
